import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'package:personal_media_archiver/core/cookies/cookies_service.dart';

class _FakePathProvider extends PathProviderPlatform with MockPlatformInterfaceMixin {
  _FakePathProvider(this.docDir);
  final String docDir;
  @override
  Future<String?> getApplicationDocumentsPath() async => docDir;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late Directory tempDir;
  late CookiesService service;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('cookies_test_');
    PathProviderPlatform.instance = _FakePathProvider(tempDir.path);
    service = CookiesService();
  });

  tearDown(() async {
    if (await tempDir.exists()) {
      await tempDir.delete(recursive: true);
    }
  });

  Future<File> writeFixture(String content, [String name = 'fixture.txt']) async {
    final f = File('${tempDir.path}/$name');
    await f.writeAsString(content);
    return f;
  }

  group('CookiesService.import', () {
    test('valid Netscape + youtube domain → meta has hasYouTube=true', () async {
      final file = await writeFixture(
        '# Netscape HTTP Cookie File\n'
        '# generated by test\n'
        '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tCONSENT\tYES+test\n'
        '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tVISITOR_INFO1_LIVE\ttest\n',
      );
      final meta = await service.import(file);
      expect(meta.hasYouTube, isTrue);
      expect(meta.domainCount, 1);
      expect(meta.lineCount, 2);
      expect(await service.exists(), isTrue);
      final p = await service.path();
      expect(p, isNotNull);
      expect(p, endsWith('/ytdlp/youtube.cookies.txt'));
    });

    test('missing Netscape header throws CookiesValidationException', () async {
      final file = await writeFixture(
        '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tCONSENT\tYES\n',
      );
      expect(
        () => service.import(file),
        throwsA(isA<CookiesValidationException>()),
      );
    });

    test('missing youtube.com domain throws CookiesValidationException', () async {
      final file = await writeFixture(
        '# Netscape HTTP Cookie File\n'
        '.example.com\tTRUE\t/\tTRUE\t1900000000\tFOO\tBAR\n',
      );
      expect(
        () => service.import(file),
        throwsA(isA<CookiesValidationException>()),
      );
    });

    test('remove deletes the file', () async {
      final file = await writeFixture(
        '# Netscape HTTP Cookie File\n'
        '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tFOO\tBAR\n',
      );
      await service.import(file);
      expect(await service.exists(), isTrue);
      await service.remove();
      expect(await service.exists(), isFalse);
      expect(await service.meta(), isNull);
    });

    test('meta() re-reads file and counts domains correctly', () async {
      final file = await writeFixture(
        '# Netscape HTTP Cookie File\n'
        '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tA\tB\n'
        '.google.com\tTRUE\t/\tTRUE\t1900000000\tC\tD\n'
        '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tE\tF\n',
      );
      await service.import(file);
      final meta = await service.meta();
      expect(meta, isNotNull);
      expect(meta!.hasYouTube, isTrue);
      expect(meta.domainCount, 2);
      expect(meta.lineCount, 3);
    });

    test('importFromContent works without File (share intent path)', () async {
      const content =
          '# Netscape HTTP Cookie File\n'
          '# from Android share intent\n'
          '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tSID\ttoken\n';
      final meta = await service.importFromContent(content);
      expect(meta.hasYouTube, isTrue);
      expect(meta.domainCount, 1);
      expect(await service.exists(), isTrue);
    });

    test('importFromContent rejects invalid content', () async {
      const badContent = '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tSID\ttoken\n';
      expect(
        () => service.importFromContent(badContent),
        throwsA(isA<CookiesValidationException>()),
      );
    });

    test('importFromContent accepts #HttpOnly_.youtube.com rows', () async {
      // YouTube auth cookies (SID/HSID/SSID/SAPISID) 通常 export 為 HttpOnly
      // Netscape format: `#HttpOnly_` prefix 是 cookie row 不是 comment
      const content =
          '# Netscape HTTP Cookie File\n'
          '# generated by browser extension\n'
          '#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tSID\tauth_token\n'
          '#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tHSID\thsid_token\n'
          '.youtube.com\tTRUE\t/\tTRUE\t1900000000\tCONSENT\tYES\n';
      final meta = await service.importFromContent(content);
      expect(meta.hasYouTube, isTrue);
      expect(meta.domainCount, 1); // .youtube.com unique
      expect(meta.lineCount, 3); // 2 HttpOnly + 1 plain
    });

    test('importFromContent skips real comments but parses HttpOnly cookies', () async {
      const content =
          '# Netscape HTTP Cookie File\n'
          '# This is a real comment line\n'
          '# Another comment\n'
          '#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tSID\ttoken\n';
      final meta = await service.importFromContent(content);
      expect(meta.hasYouTube, isTrue);
      expect(meta.lineCount, 1); // only the HttpOnly counts
    });
  });
}
